# Generated by Django 3.0.5 on 2020-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('etiqueta', models.SlugField(verbose_name='Etiqueta')),
            ],
        ),
    ]
